### ISSUE TITLE
ImportError undefined symbol: _Py_Dealloc

### ISSUE THREAD

**Issue by initbar** [dgrunwald/rust-cpython#122]
Hello ~ I'm trying to learn the interface between Rust and Python - but I can't find the solution as to why I can't seem to import my compiled library (even using the code from the [rust example](https://dgrunwald.github.io/rust-cpython/doc/cpython/macro.py_module_initializer.html)).

The below build is from [blaze](https://github.com/initbar/blaze):

![screenshot](https://user-images.githubusercontent.com/12630151/35260300-c9410b96-ffd8-11e7-93e6-f302ac78d6e5.png)

If there are any pointers (or a section in a documentation) where I can read and try to figure out the answer, I would appreciate the help :smiley:

**Comment by initbar** [comment]
@dgrunwald I've read the comment in issue #87, and realized that `cargo` was building against the Python 3 libraries. In that case, is it possible to provide flags to `cargo build` in such ways that both Python 2.7+ and Python 3.+ are supported?

**Comment by initbar** [comment]
Figured it out ~
```toml
[dependencies.cpython]
version = "0.1"

# Python 2.7
default-features = false
features = ["extension-module-2-7", "python27-sys"]

# Python 3+
# features = "extension-module"
```
